$('.owl-carousel').owlCarousel({
    loop:true,
    margin:10,
    autoplay:true,
    autoplayTimeout:1000,
    autoplayHoverPause:true,
    nav:true,
    DelayNode
    responsive:{
        0:{
            items:2
        },
        425:{
            items:3
        },
        768:{
            items:4
        },
        1000:{
            items:6
        }
        
    }
})